[package]
name = "soft_render"
version = "0.1.0"
authors = ["doup <asier@illarra.com>"]

[dependencies]
wavefront_obj = "5.1.0"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["gfx"]
